### PR TITLE
feat: adds timezone support

### LINKED ISSUE #221: Add ability to set timezone
Needed for:
- Calculation of users' stats.
- Displaying correct graph for users' timezones.

JSON list: https://github.com/dmfilipenko/timezones.json
Detection: http://pellepim.bitbucket.org/jstz/

### LINKED ISSUE #232: Evening meditations showing on the following day in stats
Recently my evening meditations have started showing on the 10 day chart as having occurred the following day.  No doubt a time zone issue.

### PR DESCRIPTION
**Pull request by binarious**
Depends on https://github.com/Sirimangalo/meditation-plus-server/pull/34
Fixes #221, fixes #232

### CODE REVIEW

**Comment by olastor** [comment]
If I change the timezone, the meditation graph in 'Home' stays unaffected. Is this correct?

**Comment by binarious** [comment]
No, it should change and does for me.

Sebastian K. <notifications@github.com> schrieb am Mo., 29. Aug. 2016,
23:34:

**Comment by olastor** [comment]
It changes the chart, but I have to restart the browser first. Is the chart data somewhere chached?

**Comment by binarious** [comment]
Just in the client. A reload should be enough.

**Pull request merged**
