### PR TITLE
fix(auth-http): wrap instead of extends

### PR DESCRIPTION
**Pull request by binarious**

### CODE REVIEW

**Comment by olastor** [comment]
I am getting a bunch of `400 Bad requests` when testing it locally.

**Comment by binarious** [comment]
Can you give me an example?

**Comment by olastor** [comment]
`{"errors":{"text":{"message":"Path `text` is required.","name":"ValidatorError","properties":{"type":"required","message":"Path `{PATH}` is required.","path":"text"},"kind":"required","path":"text"}},"message":"Message validation failed","name":"ValidationError"}`

**Comment by binarious** [comment]
https://github.com/Sirimangalo/meditation-plus-angular/pull/436

**Pull request closed without merging**
