### PR TITLE
feat(profile): adds basic stats

### LINKED ISSUE #50: Stats
Just copying that from https://github.com/yuttadhammo/meditation-plus-server/issues/2 so it doesn't get lost. We should create separate issues for this ideas when we find the time.

# Consecutive Days
- Display the number of consecutive days
- Reward multiple consecutive days with badges

# Previous Meditations (Statistics)
- Show graphs for the last 10 days, 10 weeks and 10 months
- Display the number of sessions (per day)
- Display the percentage of days with a session (since first app usage)
- Display total meditation time, average session time and longest session time

### PR DESCRIPTION
**Pull request by binarious**
Closes #50

### CODE REVIEW

**Comment by olastor** [comment]
Probably should discuss with @yuttadhammo  whether the `longest session` tag is appropriate.

**Comment by binarious** [comment]
Right. @yuttadhammo do you see any problems with the stats in this table? https://github.com/Sirimangalo/meditation-plus-angular/pull/125/files#diff-c7a1b63f8dca95b0b8647172cfffa63fR51

**Comment by yuttadhammo** [comment]
Yeah, maybe longest session isn't necessary

**Comment by binarious** [comment]
Done

**Pull request merged**
